version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  generate-password:
    lang: python3-http
    handler: ./generate-password
    image: liampulsation/generate-password:latest
    environment:
      db_host: "cofrap-db-svc"
      db_port: 5432
      db_name: "cofrap"
      db_user: "cofrap"
    secrets:
      - secret-key
      - password-db
    annotations:
      com.openfaas.scale.zero: "true"

  generate-2fa:
    lang: python3-http
    handler: ./generate-2fa
    image: liampulsation/generate-2fa:latest
    environment:
      db_host: "cofrap-db-svc"
      db_port: 5432
      db_name: "cofrap"
      db_user: "cofrap"
    secrets:
      - secret-key
      - password-db
    annotations:
      com.openfaas.scale.zero: "true"

  authenticate:
    lang: python3-http
    handler: ./authenticate
    image: liampulsation/authenticate:latest
    environment:
      db_host: "cofrap-db-svc"
      db_port: 5432
      db_name: "cofrap"
      db_user: "cofrap"
    secrets:
      - secret-key
      - password-db
    annotations:
      com.openfaas.scale.zero: "true"
